# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
jobs:
  - job: build_mapd_core_cpu
    pool:
      vmImage: 'macOS 10.13'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createCustomEnvironment: True
          packageSpecs: conda-build python=$(python.version) anaconda-client
          installOptions: --channel conda-forge
          updateConda: True
          environmentName: mapd-core-cpu
      - script: |
          sudo chown -R 501:20 /usr/local/miniconda/envs
          conda config --set always_yes True
          conda config --add channels conda-forge
          conda config --add channels omnisci
        displayName: 'Conda config'
      - script: conda build mapd-core-cpu
        displayName: 'Conda build mapd-core'
      - script: |
          anaconda --token $(ANACONDA_TOKEN) \
            upload --user $(ANACONDA_USER) --label $(ANACONDA_LABEL) \
            /usr/local/miniconda/envs/mapd-core-cpu/conda-bld/**/mapd-core-cpu-*.tar.bz2
        displayName: 'Upload mapd-core-package'

  - job: install_mapd_core
    pool:
      vmImage: 'macOS 10.13'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createCustomEnvironment: True
          packageSpecs: python=$(python.version)
          installOptions: --channel conda-forge
          updateConda: True
          environmentName: mapd-core-cpu
      - script: |
          sudo chown -R 501:20 /usr/local/miniconda/envs
          conda config --set always_yes True
          conda config --add channels conda-forge
          conda config --add channels quansight
          conda config --add channels omnisci
        displayName: 'Conda config'
      - script: conda install -c quansight/label/$(ANACONDA_LABEL) mapd-core-cpu
        displayName: 'INSTALL MAPD-CORE-CPU'
      - script: cd $CONDA_PREFIX/bin && cp mapd_initdb initdb
        displayName: 'COPY MAPD_INITDB AS INITDB'
      - script: cd $CONDA_PREFIX/systemd && ./install_mapd_systemd.sh
        displayName: 'INSTALL MAPD SYSTEMD'
      - script: systemctl start mapd_server
        displayName: 'START MAPD SERVER'
