# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
jobs:
  - job: build_mapd_core_cpu
    pool:
      vmImage: 'macOS 10.13'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createCustomEnvironment: True
          packageSpecs: conda-build python=$(python.version) anaconda-client
          installOptions: --channel conda-forge
          updateConda: True
          environmentName: mapd-core-cpu
      - script: |
          export CONDA_ROOT=$HOME/.conda
          sudo chown -R 501:20 $CONDA_ROOT/envs
          conda config --set always_yes True
          conda config --add channels conda-forge
          conda config --add channels omnisci
        displayName: 'Conda config'
      - script: conda build mapd-core-cpu
        displayName: 'Conda build mapd-core'
      - script: |
          anaconda --token "$ANACONDA_TOKEN" \
            upload --user "$ANACONDA_USER" --label "$ANACONDA_LABEL" \
            $CONDA_PREFIX/conda-bld/**/mapd-core-cpu-*.tar.bz2
        displayName: 'Upload mapd-core-package'

  - job: install_mapd_core
    dependsOn: build_mapd_core_cpu
    pool:
      vmImage: 'macOS 10.13'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createCustomEnvironment: True
          packageSpecs: python=$(python.version)
          installOptions: --channel conda-forge
          updateConda: True
          environmentName: mapd-core-cpu
      - script: |
          export CONDA_ROOT=$HOME/.conda
          sudo chown -R 501:20 "$CONDA_ROOT/envs"
          conda config --set always_yes True
          conda config --add channels conda-forge
          conda config --add channels "$ANACONDA_USER"
          conda config --add channels omnisci
        displayName: 'Conda config'
      - script: conda install -c "$ANACONDA_USER"/label/"$ANACONDA_LABEL" mapd-core-cpu
        displayName: 'INSTALL MAPD-CORE-CPU'
      - script: |
          conda install bash
          /usr/bin/env bash --version
          cd $CONDA_PREFIX
          chmod +x "${CONDA_PREFIX}/mapd-install.sh"
          ./mapd-install.sh
          conda uninstall bash
        displayName: 'Install MapD service and server'
      - script: $CONDA_PREFIX/bin/mapd_server --config "$CONDA_PREFIX/data/mapd.conf"
        displayName: 'Start MapD server'

