# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
jobs:
  - job: build_mapd_core_cpu
    pool:
      vmImage: 'macOS 10.13'
    steps:
      - task: CondaEnvironment@1
        inputs:
          createCustomEnvironment: False
          packageSpecs: conda-build
          installOptions: --channel conda-forge
          updateConda: True
      - script: conda config --add channels conda-forge && conda config --add channels omnisci
        displayName: 'Add conda-forge channel'
      - script: conda build mapd-core-cpu
        displayName: 'Conda build mapd-core-cpu'
      - script: conda create --name mapd-core-cpu -y
        displayName: 'Create mapd-core-cpu environment'
      - script: source activate mapd-core-cpu
        displayName: 'Activate mapd-core-cpu'
      - script: conda install --use-local mapd-core-cpu -y
        displayName: 'Install mapd-core-cpu'
      - script: cd $CONDA_PREFIX/bin && cp mapd_initdb initdb
        displayName: 'Copy mapd_initdb to initdb'
      - script: cd $CONDA_PREFIX/systemd && ./install_mapd_systemd.sh
        displayName: 'INSTALL MAPD SYSTEMD'
      - script: systemctl start mapd_server
