# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
jobs:
  - job: build_mapd_core_cpu
    pool:
      vmImage: 'macOS 10.13'
    steps:
      # - task: Xcode@5
      #   inputs:
      #     actions: 'build'
      #     scheme: ''
      #     sdk: 'macosx10.13'
      #     configuration: 'Release'
      #     xcodeVersion: '9' # Options: 8, 9, default, specifyPath
      - task: CondaEnvironment@1
        inputs:
          #createCustomEnvironment: # Optional
          #environmentName: # Required when createCustomEnvironment == True
          #packageSpecs: 'python=3' # Optional
          #updateConda: # Optional
          #installOptions: # Optional
          #createOptions: # Optional
          #cleanEnvironment: # Optional
          createCustomEnvironment: False
          packageSpecs: conda-build
          installOptions: --channel conda-forge
          updateConda: True
      - script: conda config --add channels conda-forge
        displayName: 'Add conda-forge channel'
      - script: conda build mapd-core-cpu
        displayName: 'Conda build mapd-core-cpu'
      - script: conda create --name mapd-core-cpu
        displayName: 'Create mapd-core-cpu environment'
      - script: source activate mapd-core-cpu
        displayName: 'Activate mapd-core-cpu'
      - script: conda install --use-local mapd-core-cpu
        displayName: 'Install mapd-core-cpu'
      - script: cd $CONDA_PREFIX/bin && cp mapd_initdb initdb
        displayName: 'Copy mapd_initdb to initdb'
