{% set name = "mapd-core-cpu" %}
{% set version = "4.4.2" %}
{% set sha256 = "0e2ee8953e94962590f5ede6a8aa6aaefef60d747acd42dfbe925f2ad0f90a43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapd/mapd-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - arrow-cpp=0.11.0
    - bisonpp
    - blosc
    - boost-cpp=1.67
    # - boost=1.67  # [linux]
    - clangdev=6
    # - cython  # [linux]
    - double-conversion
    # - doxygen
    - flex
    - gdal
    - gflags
    - git
    - glog
    - go
    - gperftools
    - libarchive
    - libkml
    - libpng
    - llvmdev=6
    - maven
    # - numba>=0.40  # [linux]
    # - numpy>=1.14  # [linux]
    - openjdk=8
    - openssl
    - parquet-cpp
    - pyarrow=0.11.0
    # - python=3.6
    - thrift-cpp=0.11.0
    # - thrift=0.11.0
    - wget
  run:
    - arrow-cpp=0.11.0
    - bisonpp
    - blosc
    - boost-cpp=1.67
    # - boost=1.67  # [linux]
    - clangdev=6
    # - cython  # [linux]
    - double-conversion
    # - doxygen
    - flex
    - gdal
    - gflags
    # - git
    - glog
    - go
    - gperftools
    - libarchive
    - libkml
    - libpng
    - llvmdev=6
    - maven
    # - numba>=0.40  # [linux]
    # - numpy>=1.14  # [linux]
    - openjdk=8
    - openssl
    - parquet-cpp
    - pyarrow=0.11.0
    - python=3.6
    - thrift-cpp=0.11.0
    # - thrift=0.11.0
about:
  home: https://www.mapd.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The MapD Core database'

  description: |
    MapD Core is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.mapd.com/docs/
  dev_url: https://github.com/mapd/mapd-core

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
